---
- name: Stop and disable Xray service
  systemd:
    name: xray
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove Xray systemd unit
  file:
    path: /etc/systemd/system/xray.service
    state: absent

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Remove Xray binary
  file:
    path: "{{ xray_bin_path }}"
    state: absent

- name: Remove Xray installation and config directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ xray_install_dir }}"
    - "{{ xray_config_dir }}"
    - "{{ xray_client_output_dir }}"

- name: Remove specific functional dependencies
  ansible.builtin.apt:
    name:
      - unzip
    state: absent

- name: Remove xray system user
  user:
    name: xray
    state: absent
    remove: no

- name: Remove xray system group
  group:
    name: xray
    state: absent
